# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'

- task: DotNetCoreCLI@2
  name: 'Restore Nuget'
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    noCache: true

- task: DotNetCoreCLI@2
  name: 'Build Source'
  inputs:
    command: 'build'
    projects: '/src/xAPI/xAPI/xAPI*.csproj'


- task: DotNetCoreCLI@2
  name: 'Build Test Projects'
  inputs:
    command: 'build'
    projects: '/test/xAPI.Tests/xAPI.Tests.csproj'

- task: DotNetCoreCLI@2
  name: 'Run Tests'
  inputs:
    command: 'test'
    projects: '**/test/xAPI.Tests/xAPI.Tests.csproj'

